docs/modules/ROOT/pages/object-storage/usage.adoc

Some more suggestions how to use the S3 bucket.

Add some tools and client libraries

---

docs/modules/ROOT/pages/exoscale-dbaas/mysql/create.adoc
docs/modules/ROOT/pages/exoscale-dbaas/mysql/usage.adoc
docs/modules/ROOT/pages/exoscale-dbaas/postgresql/create.adoc
docs/modules/ROOT/pages/exoscale-dbaas/postgresql/usage.adoc
docs/modules/ROOT/pages/exoscale-dbaas/redis/create.adoc
docs/modules/ROOT/pages/exoscale-dbaas/redis/usage.adoc
docs/modules/ROOT/pages/object-storage/create.adoc
docs/modules/ROOT/pages/object-storage/usage.adoc

To be merged after APPCAT-273
Todo:

Adjust apiVersions in examples

---

docs/modules/ROOT/pages/object-storage/create.adoc

The change in #11 was a bit too rambazamba

ObjectBucket does not have a csp prefix

---

Makefile
docs/modules/ROOT/pages/index.adoc

Added the name for the second dimension to the object storage table.
Provider - Exoscale/Cloudscale
Zone - CH-GVA-2 0/LPG-2

Update object storage table

---

docs/modules/ROOT/pages/index.adoc

We won't provide VSHN-managed PostgreSQL on Exoscale in the near future

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/index.adoc

Fix various naming issues

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/index.adoc

Fix naming for VSHN managed resources.

Fix VSHN naming

---

docs/modules/ROOT/pages/vshn-managed/postgresql/index.adoc

Fix PostgreSQL by VSHN naming

---

docs/modules/ROOT/pages/references/crds.adoc

Add VSHNPostgreSQLBackup API docs

---

docs/modules/ROOT/nav.adoc

Add nav entry for new Redis by VSHN offering

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/apiserver/how-to.adoc
docs/modules/ROOT/pages/index.adoc

This PR adds end user documentation for our AppCat API Server.

End user docs for apiserver

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/references/crds.adoc
docs/modules/ROOT/pages/vshn-managed/redis/create.adoc
docs/modules/ROOT/pages/vshn-managed/redis/plans.adoc

Pretty much the same thing as #44 just for Redis.  Implementation PR: https://github.com/vshn/component-appcat/pull/120

Add documentation of Plans for Redis by VSHN

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/references/crds.adoc
docs/modules/ROOT/pages/vshn-managed/postgresql/update-strategy.adoc

Adds the documentation of the UpdateStrategy feature implemented in https://github.com/vshn/component-appcat/pull/137 and https://github.com/vshn/appcat-comp-functions/pull/23

Add documentation of the PostgreSQL Update Strategy

---

docs/modules/ROOT/pages/vshn-managed/postgresql/alerting.adoc

This PR documents the use of the email alerting feature

Document email alerting feature

---

docs/modules/ROOT/pages/exoscale-dbaas/kafka/create.adoc
docs/modules/ROOT/pages/exoscale-dbaas/kafka/usage.adoc

Fixed wrong CRD on Apache Kafka documentation

---

docs/modules/ROOT/pages/vshn-managed/postgresql/backup.adoc

Add more details on how postgres backups work.

Update postgres backup documentation

---

docs/modules/ROOT/pages/vshn-managed/postgresql/maintenance.adoc

note postgres maintenance repack

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/vshn-managed/redis/restore.adoc

This adds the end-user documentation on how to restore a redis instance.

Add documentation on restoring redis instances

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/vshn-managed/postgresql/connect.adoc

Short docs explaining how to connect to VSHNPostgreSQL via new service.

docs explaining how to connect to PSQL in various ways

---

docs/modules/ROOT/pages/object-storage/references.adoc

This will make it clearer for users how to handle multiple Minio
instances on the cluster.

Extend ObjectBucket references with Minio

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/references/crds.adoc
docs/modules/ROOT/pages/references/secrets.adoc
docs/modules/ROOT/pages/vshn-managed/keycloak/create.adoc
docs/modules/ROOT/pages/vshn-managed/keycloak/delete.adoc
docs/modules/ROOT/pages/vshn-managed/keycloak/index.adoc
docs/modules/ROOT/pages/vshn-managed/keycloak/maintenance.adoc
docs/modules/ROOT/pages/vshn-managed/keycloak/plans.adoc
docs/modules/ROOT/pages/vshn-managed/keycloak/restore.adoc
docs/modules/ROOT/pages/vshn-managed/keycloak/usage.adoc
docs/modules/ROOT/pages/vshn-managed/mariadb/index.adoc
docs/modules/ROOT/pages/vshn-managed/postgresql/index.adoc
docs/modules/ROOT/pages/vshn-managed/redis/index.adoc

Add Keycloak docs

---

docs/modules/ROOT/pages/vshn-managed/how-tos/logging.adoc

Making the log documentation a bit more service generic.

Update log documentation

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/index.adoc
docs/modules/ROOT/pages/references/secrets.adoc
docs/modules/ROOT/pages/vshn-managed/keycloak/create.adoc
docs/modules/ROOT/pages/vshn-managed/nextcloud/create.adoc
docs/modules/ROOT/pages/vshn-managed/nextcloud/delete.adoc
docs/modules/ROOT/pages/vshn-managed/nextcloud/index.adoc
docs/modules/ROOT/pages/vshn-managed/nextcloud/plans.adoc
docs/modules/ROOT/pages/vshn-managed/nextcloud/security.adoc
docs/modules/ROOT/pages/vshn-managed/nextcloud/usage.adoc

This PR adds the end-user docs for the new Nextcloud offering

Add End-User docs for Nextcloud

---

docs/modules/ROOT/pages/vshn-managed/nextcloud/create.adoc
docs/modules/ROOT/pages/vshn-managed/nextcloud/usage.adoc

This PR fixes a wrong version in the nextcloud examples

Fix wrong version for the nextcloud examples

---

.gitignore
docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/vshn-managed/how-tos/custom-image-keycloak.adoc
docs/modules/ROOT/pages/vshn-managed/keycloak/customization.adoc

This is documentation how to customize your Keyclock instance.

Keyclock customization

---

docs/modules/ROOT/pages/vshn-managed/keycloak/customization.adoc

This PR documents how to create and use a custom configuration and custom environment variables

Document custom configuration and env variables for Keycloak

---

docs/modules/ROOT/pages/exoscale-dbaas/redis/create.adoc

should this also be added to the other exoscale services?

Add note of cloud service taking up to 5min to provision

---

docs/modules/ROOT/pages/vshn-managed/keycloak/customization.adoc

We adjusted the keycloak configMap configuration option to allow multiple keycloak configs.

Adjust customization docs for keycloak

---

docs/modules/ROOT/pages/references/alerts.adoc
docs/modules/ROOT/pages/vshn-managed/postgresql/alerting.adoc

Draft for end-user docs about the alerts.

Add Alert Documentation

---

docs/modules/ROOT/pages/vshn-managed/keycloak/create.adoc
docs/modules/ROOT/pages/vshn-managed/keycloak/customization.adoc
docs/modules/ROOT/pages/vshn-managed/keycloak/usage.adoc

Updated reference Keycloak version to 25

Keycloak v25

---

docs/modules/ROOT/pages/object-storage/delete.adoc

This PR documents the new deletionProtection for ObjectBuckets

Document deletionProtection for ObjectBuckets

---

docs/modules/ROOT/pages/vshn-managed/postgresql/create.adoc

This PR adds pg bouncer settings to the creation page of vshn postgresql.

Add pg bouncer doc

---

docs/modules/ROOT/pages/vshn-managed/postgresql/usermanagement.adoc

Changing documentation so it's easier for customers to create right collate in their PostgreSQL databases.

Change set collate in PSQL command to use templates 

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/vshn-managed/nextcloud/collabora.adoc

Small Collabora end-user documentation

adding Collabora docs

---

docs/modules/ROOT/pages/vshn-managed/postgresql/connect.adoc

Documentation how to disable TLS in VSHNPostgreSQL

add disable-TLS docs for VSHNPostgreSQL

---

docs/modules/ROOT/pages/vshn-managed/nextcloud/create.adoc
docs/modules/ROOT/pages/vshn-managed/nextcloud/usage.adoc

Nextcloud FQDN is an array not a string

Fix nextcloud fqdn

---

docs/modules/ROOT/pages/vshn-managed/postgresql/create.adoc

Fix typo in default plan for PostgreSQL

Fix typo in default plan for PostgreSQL

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/vshn-managed/postgresql/major-upgrade.adoc

This PR adds postgres major version upgrade documentation

Add postgres major upgrade docs

---

docs/modules/ROOT/pages/vshn-managed/postgresql/security.adoc

missing docs for network policies

add missing docs for network settings

---

docs/modules/ROOT/pages/vshn-managed/forgejo/create.adoc

Add documentation for customizing a Forgejo installation

Forgejo customization docs

---

docs/modules/ROOT/pages/vshn-managed/redis/create.adoc
docs/modules/ROOT/pages/vshn-managed/redis/usage.adoc

VSHNRedis default version update in the docs from 7.0 to 8.0

VSHNRedis default version update

---

docs/modules/ROOT/pages/vshn-managed/keycloak/customization.adoc

Support mounting secrets and configmaps as volumes in VSHNKeycloak

Support mounting secrets and configmaps as volumes in VSHNKeycloak 

---

docs/modules/ROOT/pages/references/crds.adoc
docs/modules/ROOT/pages/vshn-managed/keycloak/customization.adoc

- Align Keycloak CRD docs
- Align Keycloak usage docs

Update Keycloak docs

---

docs/modules/ROOT/pages/vshn-managed/forgejo/maintenance.adoc
docs/modules/ROOT/pages/vshn-managed/keycloak/maintenance.adoc
docs/modules/ROOT/pages/vshn-managed/mariadb/maintenance.adoc
docs/modules/ROOT/pages/vshn-managed/nextcloud/maintenance.adoc
docs/modules/ROOT/pages/vshn-managed/postgresql/maintenance.adoc
docs/modules/ROOT/pages/vshn-managed/redis/maintenance.adoc

Updated the maintenance window times according to this change: https://github.com/vshn/appcat/pull/451

Update maintenance window docs

---

docs/modules/ROOT/pages/vshn-managed/keycloak/customization.adoc

See here: https://www.keycloak.org/migration/migrating-to-quarkus

fix keycloak is built on quarkus, not spring

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/changelog/2025-10-07.adoc

Create AppCat Changelog 2025-10-07

Create AppCat Changelog 2025-10-07
